version: "3.7"
services:
  web1:
    container_name: web1
    build:
      context: .
    privileged: true
    volumes:
      - ./root:/var/www/html
    expose:
      - 8080
      - 8443
networks:
  default:
    external:
      name: proxy-web-link