version: "3.7"
services:
  web2:
    container_name: web2
    build:
      context: .
    privileged: true
    volumes:
      - ./root:/var/www/html
    expose:
      - 8090
      - 8453
networks:
  default:
    external:
      name: proxy-web-link